** Numerical Python which is also known as Numpy. it have a concept called numpy array which is basically 50X faster than traditional python list. It was created in 2005 by a developer called travis oliphant, it's is widely for the speed and data consistency** 

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
arr = np.array([21,45,90,'wasiq'])
print(arr)

['21' '45' '90' 'wasiq']


In [2]:
ar1 = np.array([21,45,90])
print(ar1.ndim)

1


In [2]:
ar3 = np.array([[21,34,45],[11,76,10],[11,76,10]])
print(ar3)

[[21 34 45]
 [11 76 10]
 [11 76 10]]


In [1]:
import numpy as np

In [2]:
ar3 = np.array([1, 2, 3,21,34,45,11,76,10,11,76,10])
# print(ar3[3:7])
# print(ar3[3:])
print(ar3[0:12:2])
print(ar3[::-2])

[ 1  3 34 11 10 76]
[10 11 76 45 21  2]


In [2]:
ar3 = np.array([[21,34,45],[11,76,10],[11,76,10]])
print(ar3)
print(ar3[1][0])

[[21 34 45]
 [11 76 10]
 [11 76 10]]
11


**Stastical operation**

In [2]:
ar3 = np.array([1, 2, 3,21,34,45,11,76,10,11,76,10])
np.max(ar3)  #maximum value
np.mean(ar3)  #average value
np.min(ar3)  #minimum value
np.sum(ar3)  #sum of all item
np.median(ar3)  #middle value

np.float64(11.0)

**Mathamaitical operation**

In [6]:
ar1 = np.array([2,4,6])
ar2 = np.array([8,9,10])
np.add(ar1,ar2)

array([10, 13, 16])

In [3]:
np.subtract(ar1,ar2)

array([-6, -5, -4])

In [5]:
np.multiply(ar1,ar2)

array([16, 36, 60])

In [7]:
np.divide(ar1,ar2)

array([0.25      , 0.44444444, 0.6       ])

In [12]:
x=np.random.rand()
print(x)

0.4719894408515364


In [9]:
x=np.random.rand(5)
print(x)

[0.44871568 0.33238235 0.82679473 0.69292258 0.08813318]


In [14]:
y=np.random.randint(1,10)
print(y)

5


In [17]:
z=np.random.randint(1000,9999,size=3)
print(z)

[9387 8984 8270]


In [20]:
z1=np.random.randint(100000,999999)
print(z1)


608453


In [22]:
z2=np.random.randn()
print(z2)

0.6056722276344143


In [25]:
a1=np.array([21,50,90,79,80,12])
new_arry=a1.reshape(2,3)
print(new_arry)

[[21 50 90]
 [79 80 12]]


In [29]:
a1=np.array([2,4,6,8])

In [31]:
np.power(a1,2)

array([ 4, 16, 36, 64])

In [30]:
np.sqrt(a1)

array([1.41421356, 2.        , 2.44948974, 2.82842712])